### PR TITLE
Fix crash on tap to focus due to miscalculated focus area

### PR DESCRIPTION
**Pull request by larryng**
Related issues: #87 #84 #80 #61 #34

[Only this line needed to change](https://github.com/gogopop/CameraKit-Android/blob/4c2d2a271abf8de0892db4bb23ec030ed1c8c052/camerakit/src/main/api16/com/flurgle/camerakit/Camera1.java#L617), but I couldn't help cleaning up some.

### CODE REVIEW

**Comment by tikimcfee** [comment]
@larryng Hey there, just wanted to say thanks for making a PR for this - we ran into this issue as well and have merged it into our custom version as well. Thanks again!!

**Comment by eduardo4jesus** [comment]
Hi @larryng, Thanks for taking a look at this issue.

I downloaded your code into my project. The tap gesture is not crashing as often it was before.
However I am still getting a crash. 

Here is the callstack:

```
06-02 10:10:14.337 13129-13129/com.company.appname E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.company.appname, PID: 13129
                                                                      java.lang.RuntimeException: setParameters failed
                                                                          at android.hardware.Camera.native_setParameters(Native Method)
                                                                          at android.hardware.Camera.setParameters(Camera.java:1964)
                                                                          at com.flurgle.camerakit.Camera1$5.run(Camera1.java:586)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6939)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
06-02 10:10:18.041 13129-13129/com.company.appname I/Process: Sending signal. PID: 13129 SIG: 9
```

Its crashing on  `private void resetFocus(final boolean success, final Camera camera)`.

**Comment by eduardo4jesus** [comment]
Maybe the `meteringAreas` on can't be `null`

```
 private void resetFocus(final boolean success, final Camera camera) {
        mHandler.removeCallbacksAndMessages(null);
        mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (camera != null) {
                    Log.d("blupper.debug", "run: ");
                    camera.cancelAutoFocus();
                    Camera.Parameters params = camera.getParameters();
                    if (params.getFocusMode() != Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE) {
                        Log.d("blupper.debug", "run: IF");
                        params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);
                        params.setFocusAreas(null);
                        params.setMeteringAreas(null);
                        camera.setParameters(params);
                    }

                    if (mAutofocusCallback != null) {
                        mAutofocusCallback.onAutoFocus(success, camera);
                    }
                }
            }
        }, DELAY_MILLIS_BEFORE_RESETTING_FOCUS);
    }
```

**Comment by eduardo4jesus** [comment]
Maybe `meteringAreas` can't be `null` on:

```
private void resetFocus(final boolean success, final Camera camera) {
        mHandler.removeCallbacksAndMessages(null);
        mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                if (camera != null) {
                    Log.d("blupper.debug", "run: ");
                    camera.cancelAutoFocus();
                    Camera.Parameters params = camera.getParameters();
                    if (params.getFocusMode() != Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE) {
                        Log.d("blupper.debug", "run: IF");
                        params.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);
                        params.setFocusAreas(null);
                        params.setMeteringAreas(null);
                        camera.setParameters(params);
                    }

                    if (mAutofocusCallback != null) {
                        mAutofocusCallback.onAutoFocus(success, camera);
                    }
                }
            }
        }, DELAY_MILLIS_BEFORE_RESETTING_FOCUS);
    }
```

**Comment by larryng** [comment]
@eduardo4jesus I'm unable to reproduce the crash in an emulator nor on my phone.  Regardless, it looks like that crash is caused by something else, not this patch.  I've renamed the PR to narrow the scope of this PR as to not claim to fix every tap-to-focus crash.

**Comment by eduardo4jesus** [comment]
@larryng, did you put a print inside the IF statement `if (params.getFocusMode() != Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE)` to see if it is getting called?

Not every tap gesture triggers it. Just when the focus try to reset while I am tapping. Usually I quickly click around, up and down, on the camera view. Every time `camera.setParameters(params);` it crashes. 

I understand and agree that this problem is not the focus of this PR. I appreciate your attention.

Regards.

**Comment by dwillmc** [comment]
Merging this. Thanks @larryng! @eduardo4jesus I'll make a note to try to reproduce this problem and see what I can do. This portion of the code (tap to focus overall) is getting a closer before 1.0.0.

**Comment by eduardo4jesus** [comment]
@larryng. I am still having this problem, and in the devices I have is really easy to reproduce. @dwillmc,  I didn't find the issue you mentioned regarding this problem.

**Comment by dwillmc** [comment]
@eduardo4jesus I have a day this week set aside to take care of this lib so I'll note to take a look at this

**Pull request merged**
