### PR TITLE
Added TORCH flash mode (to be used with video)

### PR DESCRIPTION
**Pull request by andreidiaconu**

### CODE REVIEW

**Comment by luongvo** [comment]
@andreidiaconu Is seems it lacks of `ckFlash` in `attrs.xml` config at https://github.com/gogopop/CameraKit-Android/blob/master/camerakit/src/main/res/values/attrs.xml#L14. Please add more item `<enum name="torch" value="3" />` here 💃

**Comment by palaciosyansro** [comment]
please launch this one!

**Comment by dwillmc** [comment]
Thanks! Merging this, I'll commit the xml attribute separately.

**Comment by andreidiaconu** [comment]
Sorry for not having the time for this lately (adding the xml attribute)

**Pull request merged**
